### ISSUE TITLE
Implement Test Cases to exercise all aspects of the library.

### ISSUE THREAD

**Issue by Du-z** [Surreal-Net/Surreal.Net#82]
Create test cases to exercise the library.

This task is to both keep track of tests that need to be written and the ones that have been written.

- [ ] Auth tests
  - [x] Root User signin #80
  - [x] Namespace User Signin, Authenticate. then query for $token. #80
  - [x] Database User Signin and Authenticate. then query for $token. #80
  - [x] Scoped User Signup, Signin and Authenticate. then query for $token and $auth. #80
  - [ ] Invalidate JWTs
- [ ] Create, Select, Delete, Update, Modify, Let, Change tests
  - [x] Basic tests #30
  - [ ] Error Responses
  - [ ] Complex ID tests
    - [ ] `temperature:{ location: 'London', date: $now }`
    - [ ] `temperature:['London', $now]`
- [ ] Query tests (With and without vars defined vars)
  - [x] Basic tests #30
  - [x] Mathematical and equality calculations #30 #44 #47
  - [x] Multi line Queries #44 #78
  - [ ] Error Responses
  - [ ] RELATE and Graph semantics
  - [ ] manually generated object structure
    - [ ] `SELECT { weekly: false, monthly: true } AS `marketing settings` FROM user;`
  - [ ] Complex ID tests
    - [ ] `SELECT * FROM person:1..1000;`
    - [ ] `SELECT * FROM temperature:['London', '2022-08-29T08:03:39']..['London', '2022-08-29T08:09:31'];`
  - [ ] Embedded JavaScript functions
- [x] Simultaneous Database Operations test #70
- [ ] Configuration Tests
- [ ] Services Tests #75
- [ ] Multiple result sets
- [x] Converters/Serialization tests #52
- [x] Strongly typed tests #30 #47
- [x] Thing tests #29
- [x] Round trip tests #16 #27
